services:
  finances_db:
    container_name: finances_db
    image: bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - financesData:/var/lib/postgresql/data

volumes:
  financesData: {}