package rbac

var RolePermissions = map[string][]string{
	"super_admin": {
		"accountability.approve",
		"accountability.reject",
		"accountability.view_requests",
		"accountability.create",
		"accountability.update",
		"accountability.view",
		"accountability.view_self",
		"accountability.delete",
		"transaction.create",
		"transaction.view",
		"transaction.edit",
		"transacton.remove",
		"supplier.create",
		"supplier.view",
		"supplier.edit",
		"supplier.remove",
	},
	"admin": {
		"accountability.approve",
		"accountability.reject",
		"accountability.view_requests",
		"accountability.create",
		"accountability.update",
		"accountability.view",
		"accountability.view_self",	
		"transaction.create",
		"transaction.view",
		"transaction.edit",
		"transacton.remove",
		"supplier.create",
		"supplier.view",
		"supplier.edit",
		"supplier.remove",
	},
	"correntista": {
		"accountability.create",
		"accountability.view_self",
	},
	"manager": {
		"accountability.view_requests",
		"accountability.create",
	},
	"financeiro": {
		"transaction.create",
		"transaction.view",
		"transaction.edit",
		"transacton.remove",
		"supplier.create",
		"supplier.view",
		"supplier.edit",
		"supplier.remove",
	},
}
